pipeline {
    agent {
        docker {
            image 'somilmor/maven-docker-java17:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        SONAR_URL = "http://<YOUR_PUBLIC_IP>:9000"
        DOCKER_IMAGE = "somil7/ultimate-cicd:${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run SonarQube Analysis') {
            steps {
                dir('app') {
                    withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                        sh '''
                        mvn sonar:sonar \
                        -Dsonar.login=$SONAR_AUTH_TOKEN \
                        -Dsonar.host.url=$SONAR_URL
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }

        stage('Update Kubernetes Manifest') {
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    sh '''
                    git config user.email "somilmor386@gmail.com"
                    git config user.name "Somil Mor"

                    sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" kubernetes/deployment.yml

                    git add kubernetes/deployment.yml
                    git commit -m "Update image to ${BUILD_NUMBER}" || true

                    git push https://${GITHUB_TOKEN}@github.com/SomilMor/springboot-cicd-pipeline.git HEAD:main
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }
    }
}